name: Test manual trigger
on:
  workflow_dispatch:
    inputs:
      message:
        description: Message
        default: Hello World
        required: true
      other:
        description: Ye?
        default: no
        required: false
jobs:
  print-message:
    name: "Up version"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: echo test
      - run: echo ${{ github.event.inputs.message}}
      - run: echo ${{ github.event.inputs.other}}
      - run: git config --global user.name '${GITHUB_ACTOR}' && git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
      - run: export VERSION=$(npm version major --git-tag-version false)
      - run: git log --format=oneline | head
      - run: echo $VERSION
      - run: git commit -am "Release major"
      - run: git tag $VERSION
      - run: git push --follow-tags origin HEAD