name: Test manual trigger
on:
  workflow_dispatch:
    inputs:
      message:
        description: Message
        default: Hello World
        required: true
      other:
        description: Ye?
        default: no
        required: false
jobs:
  print-message:
    name: "Up version"
    runs-on: ubuntu-20.04
    steps:
      - run: echo test
      - run: echo ${{ github.event.inputs.message}}
      - run: echo ${{ github.event.inputs.other}}
      - run: npm version major --git-tag-version
      - run: git push
