name: Test manual trigger
on:
  workflow_dispatch:
    inputs:
      message:
        description: Message
        default: Hello World
        required: true
      other:
        description: Ye?
        default: no
        required: false
jobs:
  release_major:
    name: "Release Major"
    runs-on: ubuntu-20.04
    steps:
      - uses: ziemniakoss/learn-github-actions/.github/workflows/reusable.yml@master
        with:
          version_type: patch